<Layout>:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    0: 0
    GridLayout:
        cols:1

        GridLayout:
            cols: 1
            text: "Output: "

        GridLayout:
            cols: 3

            Button:
                id: 1
                text:"1"
            Button:
                id: 2
                text:"2"
            Button:
                id: 3
                text:"3"
            Button:
                id: 4
                text:"4"
            Button:
                id: 5
                text:"5"
            Button:
                id: 6
                text:"6"
            Button:
                id: 7
                text:"7"
            Button:
                id: 8
                text:"8"
            Button:
                id: 9
                text:"9"
            Button:
                id: 0
                text:"0"

