<Button>
    font_size: 80
<MyGrid>
    #object id
    name: name #connection to code: connection to input
    email: email

    GridLayout:
        cols: 1
        size: root.width, root.height

        GridLayout:
            cols: 2

            Label:
                text:"Name: "
            TextInput:
                id: name
                multiline: False

            Label:
                text:"Email: "
            TextInput:
                id: email
                multiline: False

        Button:
            text:"Submit"
            on_press: root.btn()
